#ifndef ROBOT_CONFIG_H
#define ROBOT_CONFIG_H

#define ROBOT_UPDATE_PERIOD_MS 5U

#define ROBOT_START_DELAY_MS 5000U

#define MOTOR_PWM_MAX 1000
#define MOTOR_PWM_MIN (-1000)

#define ROBOT_ATTACK_PWM 700
#define ROBOT_TRACK_PWM 450
#define ROBOT_SEARCH_PWM 350
#define ROBOT_EDGE_ESCAPE_PWM 600

#define LINE_SENSOR_EDGE_THRESHOLD 2500U
#define OPPONENT_DETECT_DISTANCE_MM 800U

#endif /* ROBOT_CONFIG_H */
