#ifndef ROBOT_CONFIG_H
#define ROBOT_CONFIG_H

#define ROBOT_UPDATE_PERIOD_MS 5U

#define ROBOT_START_DELAY_MS 5000U

#define MOTOR_PWM_MAX 1000
#define MOTOR_PWM_MIN (-1000)

#define LINE_SENSOR_EDGE_THRESHOLD 2500U

#endif /* ROBOT_CONFIG_H */
